version: '3.7'

services:
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_DATABASE=ml_app_consultorio
    volumes:
      - db-data:/var/lib/mysql:cached

volumes:
  db-data:
